SAMPLE_RATIO = 3
PROGRESS_LOG_INTERVAL = 100
DBSCAN_EPS_VALUES = [0.3, 0.5, 0.7, 1.0, 1.5]
SIMILARITY_THRESHOLD = 0.7
BOUNDS_EXTRACT_LENGTH = 50
DBSCAN_MIN_SAMPLES_DIVISOR = 5
NUM_BLOCKS = 0
SUBGRAPH_SIZES_FAST = [2, 3]
SUBGRAPH_SIZES_THOROUGH = [2, 3, 4]
EXPECTED_FEATURE_COUNT = 27

# limits (in case files are too big)
MAX_NODES_FAST = 1000000
MAX_SUBGRAPHS_FAST = 1000000
MAX_PATTERNS = 1000000

# limits
MAX_BLOCKS_FULL_ANALYSIS = 2000
THOROUGH_MAX_DEPTH = float('inf')
THOROUGH_MAX_USES = float('inf')
THOROUGH_MAX_ITERATIONS = 100000
FAST_MAX_DEPTH_FULL = 200
FAST_MAX_USES_FULL = 50
FAST_MAX_DEPTH_SAMPLE = 150
FAST_MAX_USES_SAMPLE = 30
FAST_MAX_REGS = 50
FAST_MAX_ITERATIONS = 10000
MAX_NAME_LENGTH = 30
MAX_INSTRUCTIONS_PREVIEW = 10
MAX_FILES_PREVIEW = 5
MAX_COMBINATIONS_PER_SIZE = 1000

# feature
NUM_EDGES = 1
AVG_BLOCK_SIZE = 2
MAX_BLOCK_SIZE = 3
CYCLOMATIC_COMPLEXITY = 4
DEPTH = 5
AVG_BRANCHING_FACTOR = 6
LOOP_COUNT = 7
REGISTER_DIVERSITY = 8
CALL_DIVERSITY = 9
MEMORY_OPS_RATIO = 10
ARITHMETIC_OPS_RATIO = 11
CONTROL_OPS_RATIO = 12
FLOATING_POINT_OPS_RATIO = 13
CONDITION_OPS_RATIO = 14
STACK_OPS_RATIO = 15
DATA_OPS_RATIO = 16
FLAG_OPS_RATIO = 17
SPECIAL_OPS_RATIO = 18
DEF_USE_CHAIN_LENGTH = 19
REGISTER_REUSE_RATIO = 20
MEMORY_DEPENDENCY_DEPTH = 21
LIVE_RANGE_AVERAGE = 22
DATA_FLOW_COMPLEXITY = 23
ABSTRACT_ALU_RATIO = 24
ABSTRACT_MEM_RATIO = 25
ABSTRACT_CTRL_RATIO = 26